apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: phpmyadmin-namespace
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
    - name: http
      port: 80
      targetPort: 80