apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-linkerd
  namespace: wordpress-namespace
spec:
  podSelector: {}               # todos los pods del ns (incluido el sidecar)
  policyTypes: ["Egress"]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: linkerd
      # sin "ports": permite a cualquier puerto del control plane (dest/identity/policy)
