apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress-wp
  namespace: wordpress-namespace
spec:
  podSelector:
    matchLabels:
      app: my-wordpress
  policyTypes:
    - Ingress
  ingress: []
