apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-ingress
  namespace: wordpress-namespace
  annotations:
      nginx.ingress.kubernetes.io/limit-rps: "10"
      nginx.ingress.kubernetes.io/limit-burst: "20"
spec:
  ingressClassName: nginx
  rules:
  - host: www.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wploadbalancer
            port:
              number: 80
