apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mysql-namespace
  labels: 
    app: my-db
spec:
  type: ClusterIP
  selector:
    app: my-db
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306