apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-db
  namespace: mysql-namespace
  labels:
    app: my-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-db
  template:
    metadata:
      labels:
        app: my-db
    spec:
      serviceAccountName: sa-mysql
      containers:
      - name: my-db
        image: mysql:5.7
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"
        - name: MYSQL_DATABASE
          value: "tfm"
        - name: MYSQL_USER
          value: "antonio"
        - name: MYSQL_PASSWORD
          value: "12345678"
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
