apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-wp-phpmyadmin-to-mysql
  namespace: mysql-namespace
spec:
  podSelector:
    matchLabels:
      app: my-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: wordpress-namespace
          podSelector:
            matchLabels:
              app: my-wordpress
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: phpmyadmin-namespace
          podSelector:
            matchLabels:
              app: phpmyadmin
      ports:
        - protocol: TCP
          port: 3306
