apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app-to-mysql
  namespace: mysql-namespace
spec:
  podSelector:
    matchLabels:
      app: my-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: app
          podSelector:
            matchLabels:
              app: miapp-php
      ports:
        - protocol: TCP
          port: 3306
