apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: mysql-namespace
spec:
  podSelector:
    matchLabels:
      app: my-db
  policyTypes:
    - Ingress