apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-deny-egress
  namespace: mysql-namespace
spec:
  podSelector:
    matchLabels:
      app: my-db
  policyTypes: ["Egress"]
  egress: []   