apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app-to-mysql
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: miapp-php
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mysql-namespace
          podSelector:
            matchLabels:
              app: my-db
      ports:
        - protocol: TCP
          port: 3306
