apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress-app
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: miapp-php
  policyTypes:
    - Ingress
  ingress: []
