apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: wordpress-namespace
  name: wordpress-operator
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "patch"]
