apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-admin-binding
  namespace: wordpress-namespace
subjects:
  - kind: User
    name: "wp-admin-user" 
roleRef:
  kind: Role
  name: wordpress-k8s-admin
  apiGroup: rbac.authorization.k8s.io
