apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-operator-binding
  namespace: wordpress-namespace
subjects:
  - kind: User
    name: "wp-operator-user" 
roleRef:
  kind: Role
  name: wordpress-operator
  apiGroup: rbac.authorization.k8s.io