apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mysql-namespace
  name: mysql-k8s-admin
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "persistentvolumeclaims", "configmaps", "secrets"]
    verbs: ["get", "list", "create", "update", "delete", "watch"]
