apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-admin-binding
  namespace: mysql-namespace
subjects:
  - kind: User
    name: "mysql-admin-user" 
roleRef:
  kind: Role
  name: mysql-k8s-admin
  apiGroup: rbac.authorization.k8s.io
