apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: mysql-namespace
  name: mysql-operator
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "patch"]