apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-mysql
  namespace: mysql-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-operator-binding-sa
  namespace: mysql-namespace
subjects:
  - kind: ServiceAccount
    name: sa-mysql
    namespace: mysql-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-operator 