apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-phpmyadmin
  namespace: phpmyadmin-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: phpmyadmin-operator
  namespace: phpmyadmin-namespace
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints","configmaps"]
    verbs: ["get","list","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments","replicasets"]
    verbs: ["get","list","watch","patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: phpmyadmin-operator-binding-sa
  namespace: phpmyadmin-namespace
subjects:
  - kind: ServiceAccount
    name: sa-phpmyadmin
    namespace: phpmyadmin-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: phpmyadmin-operator