apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-wordpress
  namespace: wordpress-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress-operator-binding-sa
  namespace: wordpress-namespace
subjects:
  - kind: ServiceAccount
    name: sa-wordpress
    namespace: wordpress-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wordpress-operator 