apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-wordpress
  namespace: wordpress-namespace
  labels:
    app: my-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-wordpress
  template:
    metadata: 
      labels:
        app: my-wordpress
      annotations:
        linkerd.io/inject: enabled
    spec:
      serviceAccountName: sa-wordpress
      containers:
      - name: my-wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        env:
        - name: WORDPRESS_DB_HOST
          value: "mysql.mysql-namespace.svc.cluster.local"
        - name: WORDPRESS_DB_NAME
          value: "my-db"
        - name: WORDPRESS_DB_PASSWORD
          value: "admin"
        - name: WORDPRESS_DB_USER
          value: "admin"
