apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: phpmyadmin-allow-from-self-only
  namespace: phpmyadmin-namespace
spec:
  podSelector:
    matchLabels:
      app: phpmyadmin
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: phpmyadmin-namespace
      ports:
        - protocol: TCP
          port: 80
